name: Server Libs Build.

env:
  ACTIONS_RUNNER_DEBUG: false
  QT_VERSION: 6.4.2 # 5.11.1
  WORKSPACE: ${{ github.workspace }}

on:
  push:
    branches:
      - "master"
      - "AppStore"
  pull_request:
    branches:
      - "master"
      - "AppStore"
  workflow_dispatch:

jobs:
  build:
    name: Server Lib builds.
    runs-on: ubuntu-20.04 # ubuntu-latest

    steps:
    
      - name: Env Dump.
        run: |
          sudo apt-get update
          sudo apt-get install libicu-dev libglu1-mesa-dev libgl1-mesa-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/libGL.so.1 /usr/lib/libGL.so
      
      # Checkout from Master Branch of Main Repository if building for Qt 5.11.1
      # checkout from AppStore Branch of Main repository if building for Qt 6.4.2
      - name: Clone Server GitHub Repo.
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.APP_REPO }}
          token: ${{ secrets.APP_REPO_TOKEN }}
          path: ${{ github.workspace }}
          ref: master
  
      - name: Github Clone node-scrypt.
        uses: actions/checkout@v3
        with:
          repository: barrysteyn/node-scrypt # https://github.com/barrysteyn/node-scrypt.git
          path: ${{ github.workspace }}/scrypt
          ref: v1.2.0
      
      - name: Build node-scrypt.
        run: |
          bash ${{ github.workspace }}/WorkflowUtils/ServerProd/BuildNodeScrypt.sh
          
      - name: Installing Qt ${{ env.QT_VERSION }}  for Linux.
        run: |
          python3 -m pip install aqtinstall==3.1.*
          python3 -m aqt install-qt --base https://mirrors.ocf.berkeley.edu/qt/ linux desktop ${{ env.QT_VERSION }} gcc_64 -m all --outputdir ${{ github.workspace }}/qtInstall/Qt

      - name: Github Clone Qt-Secret.
        uses: actions/checkout@v3
        with:
          repository: QuasarApp/Qt-Secret # https://github.com/QuasarApp/Qt-Secret
          path: ${{ github.workspace }}/Qt-Secret/

      - name: Build Qt-Secret.
        run: |
          PATH=${{ github.workspace }}/qtInstall/Qt/${{ env.QT_VERSION }}/gcc_64/bin:$PATH
          export PATH
          export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/:${LD_LIBRARY_PATH}
          cd ${{ github.workspace }}/Qt-Secret/
          git submodule update --init --recursive
          ${{ github.workspace }}/qtInstall/Qt/${{ env.QT_VERSION }}/gcc_64/bin/qmake -r DEFINE+=WITHOUT_GUI Qt-Secret.pro CONFIG+=staticlib
          make
          sudo rm -rf ${{ github.workspace }}/lib/linux/*so*
          cp -rf ${{ github.workspace }}/Qt-Secret/src/build/release/libQt-Secret.a ${{ github.workspace }}/lib/linux/
          cp -rf ${{ github.workspace }}/Qt-Secret/src/mini-gmp/src/build/release/libQtBigInt.a ${{ github.workspace }}/lib/linux/

      - name: Checking in libs for Server.
        run: |
          cd ${{ github.workspace }}
          git config --global user.name "eye-ink"
          git config --global user.email "rjain@cybercraft.llc"
          git status
          git commit -m "$(date +'%Y-%m-%d %H:%M:%S') - Build Server Libs from GitHub Actions Script." ${{ github.workspace }}/lib/linux/*
          git push origin $GITHUB_REF

