name: Web Production. 

env:
  ACTIONS_RUNNER_DEBUG: false
  WORKSPACE: ${{ github.workspace }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Web Production Build
    runs-on: ubuntu-latest
    steps:
      - name: Production Environment Dump.
        run: |
          node --version
          npm --version
          python3 --version
      
      - name: Clone Web GitHub Repo.
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.WEB_APP_REPO }}
          token: ${{ secrets.APP_REPO_TOKEN }}
          path: ${{ github.workspace }}

      - name: Building Web App.
        run: |
          bash ${{ github.workspace }}/WorkflowUtils/WebProd/BuildingWebApp.sh

      # - name: Uploading archive Dir to GH.
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Web_Production_build
      #     path: ${{ github.workspace }}/build
